### PR TITLE
added trash functionality

### PR DESCRIPTION
**Pull request by sushmita12345**
Added trash functionality in Note App

Note Add Page:

Screenshot 2022-04-19 at 2 18 39 PM

Note Trash Page:

Screenshot 2022-04-19 at 2 19 03 PM

### CODE REVIEW

**Comment by anandsr21harshit** [comment]
image

It should be trash is empty

**Review by anandsr21harshit — APPROVED** [review]
Good to see barrel import
Looks good to merge

**Review by sanket4120 — APPROVED** [review]
Looks good to me

**Comment by sushmita12345** [comment]
Changes has been done, thank you.

**Pull request merged**
